# Generated by Django 2.2.12 on 2020-08-31 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('rating', models.FloatField()),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotes.Language')),
            ],
        ),
    ]
